src/includes/class-boldgrid-framework-title.php
=> Remove global setting as an option in basic framework

package.json, src/includes/class-boldgrid-framework-scripts.php, src/includes/class-boldgrid-framework.php, src/includes/customizer/class-boldgrid-framework-customizer.php, webpack.config.js, yarn.lock
Following steps from issue, and you should no longer receive console warnings.
=> fixes #74 configure webpack runtime path

src/assets/scss/boldgrid/_bootstrap-additions.scss
=> Fixed row margins

src/assets/scss/boldgrid/_temp.scss
This will resolve issue #164 where the fixed header would not show the appropriate background color
=> removed hard-coded background for fixed header

src/assets/scss/boldgrid/forms/_base.scss
This resolves #152 by adjusting the css of 'input' elements
=> fixed width of input elements

src/assets/scss/boldgrid/navigation/_base.scss
This PR should resolve #150 by changing the display type and alignment of the arrow / plus icons
=> adjust css for header arrow/plus icons

src/assets/scss/editor.scss
This pull request will resolve #40
=> Added css to provide consistent editor appearance

README.md, src/includes/customizer/class-boldgrid-framework-customizer-footer.php, src/includes/customizer/class-boldgrid-framework-customizer.php
=> Add host_attribution. Fixes #184

src/assets/js/customizer/controls/bgtfw-sortable-accordion.js
=> Fixes Hide SPecial Thanks Attribution capitilization issue.

src/assets/scss/customizer/controls/icons/_panel-main.scss
This adds the woocommerce icon to customizer to resolve #67
=> added woocommerce icon to customizer

src/includes/class-boldgrid-framework-comments.php
=> Apply correct filter to comment form

src/assets/js/front-end.js, src/includes/class-boldgrid-framework-scripts.php
Previous PR #202 fixed the asterisks not showing at all, but then didn't have a check for making sure that if the asterisks were disabled, that they would NOT show. This corrects that.
=> set askerisk changes to only show if enabled

src/assets/js/customizer/layout/blog/posts/layout/layout.js, src/boldgrid-theme-framework.php, src/includes/class-boldgrid-framework-api.php, src/includes/class-boldgrid-framework.php, src/includes/configs/customizer/controls.config.php
This is to continue working on #30 which was not fully resolved with #203 due to some conflicts in handling the layout type with different pages.
=> adjusted the blog_page_container() method

src/includes/customizer/class-boldgrid-framework-customizer.php
=> removed esc_js() from custom_js_output()

src/includes/configs/customizer/controls.config.php, src/includes/configs/customizer/sections.config.php
This resolves #192 by adding new controls to handle the featured images within blog posts
=> added controls for post featured images

src/assets/scss/boldgrid/_header.scss, src/assets/scss/boldgrid/footer/_footer.scss
fixes issues with margins / paddings on mobile versions after fixing #232
=> Fix mobile padding

src/assets/js/front-end.js
=> fix wp-custom-header display issues

src/assets/scss/boldgrid/_header.scss
Fixes menu alignments in 2.2.1-rc.1
=> fix css for header rows

src/assets/scss/boldgrid/_preload.scss, src/includes/class-boldgrid-framework-scripts.php, src/includes/configs/customizer/controls.config.php, src/includes/configs/customizer/sections.config.php, src/includes/configs/theme-mods.config.php
Add controls for enabling / disabling preloader that shows background image while screen is loading.
=> Add control for enabling / disabling preloader

package.json, yarn.lock
Updated version of kirki to work with Wordpress 5.5
=> updated version of kirki

src/assets/js/customizer/controls/kirki-typography.js, src/assets/json/webfonts.json, src/includes/class-boldgrid-framework.php, src/includes/configs/customizer/controls.config.php, src/includes/customizer/class-boldgrid-framework-customizer-typography.php
Add quotes to Font Families that have spaces. Ensures that these fonts are properly loaded
=> add quotes to font families with spaces

src/includes/class-boldgrid-framework-styles.php, src/includes/class-boldgrid-framework.php
This should resolve issues where Crio looses fonts when transferred using Total Upkeep
=> add validation of fonts directory

gulpfile.js, package.json
=> recreated web-fonts.png and adjusted offsets

src/includes/customizer/class-boldgrid-framework-customizer-typography.php
=> create kirki styles.css manually

gulpfile.js, package.json, src/includes/class-boldgrid-framework-compile-colors.php, src/includes/class-boldgrid-framework-scss-compile.php, src/includes/class-boldgrid-framework-scss.php, src/includes/class-boldgrid-framework-wp-fs.php, src/includes/interface-boldgrid-framework-compile.php, yarn.lock
=> Update namespacing for scssphp

gulpfile.js, package.json, src/includes/class-boldgrid-framework-compile-colors.php, src/includes/class-boldgrid-framework-scss-compile.php, src/includes/class-boldgrid-framework-scss.php, src/includes/class-boldgrid-framework-wp-fs.php, src/includes/interface-boldgrid-framework-compile.php, yarn.lock
Addresses Theme Checker issues for 5.6 release
=> Theme check fixes

src/includes/class-boldgrid-framework-api.php
=> adjust adding column widths to header layout

gulpfile.js, src/includes/class-boldgrid-framework-scss.php, yarn.lock
=> fix scssphp errors when activation

gulpfile.js, src/assets/js/customizer/controls/bgtfw-menu-locations.js, src/includes/class-boldgrid-framework-scss.php, yarn.lock
=> Wp56 fix menu locations

gulpfile.js, src/assets/js/customizer/controls/bgtfw-header-background.js, src/assets/js/front-end.js, src/includes/class-boldgrid-framework-custom-header.php, src/includes/class-boldgrid-framework-scss.php, src/includes/configs/customizer/controls.config.php, src/includes/customizer/class-boldgrid-framework-customizer.php, yarn.lock
=> Wp56 video header

README.md, package.json, src/assets/js/customizer/controls/bgtfw-sortable-accordion.js, src/boldgrid-theme-framework.php
=> Fixes #478

src/assets/js/customizer/controls/bgtfw-sortable-accordion.js
=> fixes #376

src/includes/class-boldgrid-framework-layouts-post-meta.php
=> Filter the allowed post types for Layout Metabox

src/includes/configs/customizer/controls/blog-page.controls.php, src/includes/configs/customizer/controls/blog-post.controls.php, src/includes/configs/customizer/controls/pages.controls.php
=> update contained max width control

src/assets/js/editor.js
Helps to resolve https://github.com/BoldGrid/crio-premium/issues/45
=> add class to inline mce style element

src/assets/js/customizer/typography/preview.js, src/includes/configs/customizer-options/typography.config.php
=> resolve font weights in preview

src/assets/scss/boldgrid/navigation/_base.scss
=> fix vertical menu margin / paddings

src/assets/js/customizer/typography/link-preview.js, src/includes/class-boldgrid-framework-layouts-post-meta.php, src/includes/class-boldgrid-framework-links.php, src/includes/class-boldgrid-framework-scripts.php, src/includes/configs/customizer-options/typography.config.php
=> Fix inconsistent Link hovers

src/includes/class-boldgrid-framework-layouts-post-meta.php
=> fix closing div & endif placement

package.json, yarn.lock
=> fix dependancy issues

README.md, package.json, src/assets/js/customizer/typography/link-preview.js, src/assets/scss/attributes.scss, src/assets/scss/custom-color/color-classes.scss, src/boldgrid-theme-framework.php, src/includes/class-boldgrid-framework-links.php, src/includes/class-boldgrid-framework-wrapper.php, src/includes/class-boldgrid-framework.php, src/includes/customizer/class-boldgrid-framework-customizer-colors.php, src/includes/third-party/class-boldgrid-framework-sprout-invoices.php
Resolves #755 
Resolves #750
Resolves #741
Resolves [Boldgrid:Prime#146](https://github.com/BoldGrid/prime/issues/146)
1. Install the test zip attached here:
[crio.zip](https://github.com/BoldGrid/boldgrid-theme-framework/files/9911953/crio.zip)
2. Follow the instructions in the PRs associated with each issue:
Issue #755          => [PR#760](https://github.com/BoldGrid/boldgrid-theme-framework/pull/760)
Issue #750          => [PR#759](https://github.com/BoldGrid/boldgrid-theme-framework/pull/759)
Issue #741          => [PR#761](https://github.com/BoldGrid/boldgrid-theme-framework/pull/761)
[Prime#146](https://github.com/BoldGrid/prime/issues/146) => [PR#147](https://github.com/BoldGrid/prime/pull/147)
=> Branch 2.17.2

src/assets/scss/boldgrid/_margin-fix.scss
=> adds padding to CTAs
