src/assets/scss/boldgrid/_editor-styles.scss

This adds base styles for Gutenberg buttons.
Testing markup:
```
<div class="wp-block-button"><a class="wp-block-button__link">Rounded</a></div>
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link">Outline<br></a></div>
<div class="wp-block-button is-style-squared"><a class="wp-block-button__link">Square<br></a></div>
```

add base gutenberg button styles

---

package.json
yarn.lock

The two main issues I kept seeing from with gulp and the latest node version is upath > 1.1.0 and natives > 1.1.6. 
Updating the following dependency allows you to run the build on the latest node version without updating gulp to version 4.

Update support to lts node

---

src/includes/class-boldgrid-framework.php

This resolves #173 by removing the 'boldgrid_framework_reset' action altogether, since the function it calls, Boldgrid_Framework_Activate->reset() no longer exists

removed boldgrid_framework_reset action.

---

src/includes/configs/customizer/controls.config.php

This resolves #26 by causing a full prefiew refresh when header layout changes are made.

changed header_layout transport to 'refresh'

---

src/assets/js/front-end.js

This resolves #177 by using jQuery to add the class no-seperator to the attribution links, if the screen width is 782px or less. Additionally, it changes the .attribution-theme-mods from flex-row to flex-column to give a better looking alignment.

fixed attribution alignment on phone device

---

src/assets/scss/boldgrid/_elements.scss

This resolves #25 by setting display:inline-block on .row::before and .row::after

corrected bootrstrap display issue on safari

---

src/assets/js/customizer/controls/bgtfw-background-control.js

This resolves #156 by ensuring that loadSection() runs every time 'boldgrid_customizer_refresh' event fires.

added loadSection to init()

---

src/assets/js/front-end.js
src/assets/scss/boldgrid/woocommerce/_demo-notice.scss

When enabling a WooCommerce store notice, by default it is absolute positioned at the top of the page. However, bgtfw has it adjusted to be absolute positioned at the bottom of the page. This is undesireable as the notice will not be seen unless someone scrolls to the bottom of the page.
This PR aims to resolve #39 , however, placing the notice at the very top of the page will ave other undesireable effects, such as covering the site logo, the menu, etc. Even if the notice was placed under the masthead, if the user has submenus, it wouldn't really look right. Placing it fixed bottom of the window is better in my opinion. 
There may be a feature request in the near future to give users the ability to choose the location.

Adjusted WooCommerce store notice positioning.

---

src/assets/js/front-end.js

The 3rd party package FloatLabels was causing an issue where the asterisks were not being carried over when converting the labels into the FloatLabels. This will resolve #37  by re-adding the asterisks.

added asterisks to required fields on checkout

---

src/assets/js/customizer/base-controls.js
src/assets/js/customizer/design/woocommerce/section-expand.js
src/assets/scss/customizer/controls/icons/_panel-main.scss
src/includes/class-boldgrid-framework-api.php
src/includes/class-boldgrid-framework-woocommerce.php
src/includes/class-boldgrid-framework.php
src/includes/configs/customizer/controls.config.php
src/includes/configs/customizer/sections.config.php
src/includes/customizer/class-boldgrid-framework-customizer.php

Added container controls for WooCommerce pages

---

src/assets/js/customizer/design/woocommerce/section-expand.js
src/includes/class-boldgrid-framework-api.php
src/includes/customizer/class-boldgrid-framework-customizer.php

This resolves a problem with 2.1.18-rc1 which causes errors if woocommerce is NOT installed / activated

fixed errors when woocommerce not installed

---

src/includes/configs/customizer/sections.config.php

as a result of a misunderstanding on how the controls / sections config worked, I assumed that if the section was not added, then the subsections of that section wouldn't ether. However, it appears that if a section isn't added, then the subsections just get moved up into whatever panel they're in.
Therefore, the 'bgtfw_layout_woocommerce_container' subsection was moved to the end of the file into a conditional along with the 'bgtfw_layout_woocommerce' section .
This resolves #216

moved containter subsection to 'if' conditional

---

src/assets/scss/boldgrid/_preload.scss
src/includes/class-boldgrid-framework-scripts.php
src/includes/class-boldgrid-framework.php

webfonts are loaded differently, effectively breaking the 'preloader' which should have just not been used at all anyways. This disables the controls and the preloader for 5.5 .

disable preloader for vs 5.5+

---

src/assets/js/front-end.js

fixes #490

---

src/assets/scss/boldgrid/_bootstrap-additions.scss
src/includes/class-boldgrid-framework-api.php
src/includes/configs/customizer/controls/blog-page.controls.php
src/includes/configs/customizer/controls/blog-post.controls.php
src/includes/configs/customizer/controls/pages.controls.php

add control for 'contained full width'

---

src/assets/js/customizer/edit.js
src/includes/class-boldgrid-framework-api.php
src/includes/class-boldgrid-framework.php

this is to help resolve https://github.com/BoldGrid/crio-premium/issues/69

Change sticky toggles

---

src/assets/js/customizer/controls/bgtfw-sortable-accordion.js

Fix menu assignment in custom layout

---

src/includes/class-boldgrid-framework-layouts-post-meta.php

The opening div tag is only written if the post type is hierarchical, but the closing div tag is output regardless of that check. Move close div tag inside the if statement to prevent layout issues for non-hierarchical post types using layouts

Prevent extra closing div tag

---

src/assets/scss/attributes.scss

Resolves #755 
1. Install Test zip.
[crio.zip](https://github.com/BoldGrid/boldgrid-theme-framework/files/9890404/crio.zip)
2. Install Post and Page Builder.
3. Edit a page or post
4. Ensure that the sub-titles in the metabox are black ( instead of gray as shown in the attached image ).

change color of template subtitles

---

src/includes/class-boldgrid-framework-wrapper.php
src/includes/class-boldgrid-framework.php
src/includes/third-party/class-boldgrid-framework-sprout-invoices.php

Resolves [Boldgrid/Prime #146](https://github.com/BoldGrid/prime/issues/146)

change logic for determining base template with SI
